service: sigaa-api

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules: false
  serverless-offline:
    httpPort: 3000

provider:
  name: aws
  runtime: nodejs14.x
  stage: v1
  region: us-east-1
  memorySize: 256
  timeout: 30
  versionFunctions: false

functions:
  public:
    handler: src/serverless/api.handler
    events:
      - http:
          path: '/{proxy+}'
          method: ANY
          cors: true
          
